name: Docker
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Make jar file
        run: ./gradlew cli:shadowJar

      - uses: actions/upload-artifact@v2
        with:
          name: ontomalizer-cli
          path: cli/build/libs/*.jar

  docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - uses: actions/download-artifact@v2
        with:
          name: ontomalizer-cli
          path: cli/build/libs/

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: robotka/ontomalizer-cli:master
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
