name: Sonarqube
on:
  push:
    branches:
      - master
      - sonarqube

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Sonarqube analyze
        run: ./gradlew libsonarqube \
            -Dsonar.projectKey=lib-v-dqw4w9wgxcq \
            -Dsonar.host.url=https://sonarqube.maze.sch.bme.hu \
            -Dsonar.login=e9b53371023fbe4193c5c0df5346d47d52db320d
